// Code generated by branchkit-gen from plugin.json `action_types`. DO NOT EDIT.
// Regenerate from the plugin directory: branchkit-gen --plugin .

package main

import "github.com/branchkit/plugin-sdk-go"

// CycleWindowParams is the params shape for action "placement.cycle_window (Next Window of This App)".
type CycleWindowParams struct {
}

// HandleCycleWindow registers a typed handler for action "placement.cycle_window (Next Window of This App)".
func HandleCycleWindow(p *branchkit.Plugin, fn branchkit.ActionHandlerFunc) {
	p.HandleAction("placement.cycle_window", fn)
}

// DeskSwitchParams is the params shape for action "placement.desk_switch (Switch Desktop)".
type DeskSwitchParams struct {
	Space string `json:"space"`
}

// HandleDeskSwitch registers a typed handler for action "placement.desk_switch (Switch Desktop)".
func HandleDeskSwitch(p *branchkit.Plugin, fn func(DeskSwitchParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "placement.desk_switch", fn)
}

// MoveToSpaceParams is the params shape for action "placement.move_to_space (Move Window to Space)".
type MoveToSpaceParams struct {
	Space    string  `json:"space"`
	Stay     *bool   `json:"stay,omitempty"`
	WindowID *string `json:"window_id,omitempty"`
}

// HandleMoveToSpace registers a typed handler for action "placement.move_to_space (Move Window to Space)".
func HandleMoveToSpace(p *branchkit.Plugin, fn func(MoveToSpaceParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "placement.move_to_space", fn)
}

// OverviewParams is the params shape for action "placement.overview (Show All Windows)".
type OverviewParams struct {
}

// HandleOverview registers a typed handler for action "placement.overview (Show All Windows)".
func HandleOverview(p *branchkit.Plugin, fn branchkit.ActionHandlerFunc) {
	p.HandleAction("placement.overview", fn)
}

// SnapPosition is a generated enum type.
type SnapPosition string

const (
	SnapPositionLeft     SnapPosition = "left"
	SnapPositionRight    SnapPosition = "right"
	SnapPositionMaximize SnapPosition = "maximize"
	SnapPositionCenter   SnapPosition = "center"
	SnapPositionNext     SnapPosition = "next"
	SnapPositionPrev     SnapPosition = "prev"
)

// SnapParams is the params shape for action "placement.snap (Snap Window)".
type SnapParams struct {
	Position *SnapPosition `json:"position,omitempty"`
}

// HandleSnap registers a typed handler for action "placement.snap (Snap Window)".
func HandleSnap(p *branchkit.Plugin, fn func(SnapParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "placement.snap", fn)
}

// UndoParams is the params shape for action "placement.undo (Put Window Back)".
type UndoParams struct {
}

// HandleUndo registers a typed handler for action "placement.undo (Put Window Back)".
func HandleUndo(p *branchkit.Plugin, fn branchkit.ActionHandlerFunc) {
	p.HandleAction("placement.undo", fn)
}
