// Code generated by branchkit-gen from plugin.json `action_types`. DO NOT EDIT.
// Regenerate from the plugin directory: branchkit-gen --plugin .

package main

import "github.com/branchkit/plugin-sdk-go"

// BringBackParams is the params shape for action "placement.bring_back (Bring Back a Minimized Window)".
type BringBackParams struct {
	App *string `json:"app,omitempty"`
}

// HandleBringBack registers a typed handler for action "placement.bring_back (Bring Back a Minimized Window)".
func HandleBringBack(p *branchkit.Plugin, fn func(BringBackParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "placement.bring_back", fn)
}

// CloseParams is the params shape for action "placement.close (Close Window)".
type CloseParams struct {
	App *string `json:"app,omitempty"`
}

// HandleClose registers a typed handler for action "placement.close (Close Window)".
func HandleClose(p *branchkit.Plugin, fn func(CloseParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "placement.close", fn)
}

// CycleWindowParams is the params shape for action "placement.cycle_window (Next Window of This App)".
type CycleWindowParams struct {
}

// HandleCycleWindow registers a typed handler for action "placement.cycle_window (Next Window of This App)".
func HandleCycleWindow(p *branchkit.Plugin, fn branchkit.ActionHandlerFunc) {
	p.HandleAction("placement.cycle_window", fn)
}

// DeskSwitchParams is the params shape for action "placement.desk_switch (Switch Desktop)".
type DeskSwitchParams struct {
	Space string `json:"space"`
}

// HandleDeskSwitch registers a typed handler for action "placement.desk_switch (Switch Desktop)".
func HandleDeskSwitch(p *branchkit.Plugin, fn func(DeskSwitchParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "placement.desk_switch", fn)
}

// FullscreenParams is the params shape for action "placement.fullscreen (Toggle Full Screen)".
type FullscreenParams struct {
	App *string `json:"app,omitempty"`
}

// HandleFullscreen registers a typed handler for action "placement.fullscreen (Toggle Full Screen)".
func HandleFullscreen(p *branchkit.Plugin, fn func(FullscreenParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "placement.fullscreen", fn)
}

// MinimizeParams is the params shape for action "placement.minimize (Minimize Window)".
type MinimizeParams struct {
	App *string `json:"app,omitempty"`
}

// HandleMinimize registers a typed handler for action "placement.minimize (Minimize Window)".
func HandleMinimize(p *branchkit.Plugin, fn func(MinimizeParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "placement.minimize", fn)
}

// MoveToSpaceParams is the params shape for action "placement.move_to_space (Move Window to Space)".
type MoveToSpaceParams struct {
	Space    string  `json:"space"`
	Stay     *bool   `json:"stay,omitempty"`
	WindowID *string `json:"window_id,omitempty"`
	App      *string `json:"app,omitempty"`
}

// HandleMoveToSpace registers a typed handler for action "placement.move_to_space (Move Window to Space)".
func HandleMoveToSpace(p *branchkit.Plugin, fn func(MoveToSpaceParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "placement.move_to_space", fn)
}

// OverviewParams is the params shape for action "placement.overview (Show All Windows)".
type OverviewParams struct {
}

// HandleOverview registers a typed handler for action "placement.overview (Show All Windows)".
func HandleOverview(p *branchkit.Plugin, fn branchkit.ActionHandlerFunc) {
	p.HandleAction("placement.overview", fn)
}

// PinParams is the params shape for action "placement.pin (Keep Window in Front)".
type PinParams struct {
	Pinned *bool   `json:"pinned,omitempty"`
	App    *string `json:"app,omitempty"`
}

// HandlePin registers a typed handler for action "placement.pin (Keep Window in Front)".
func HandlePin(p *branchkit.Plugin, fn func(PinParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "placement.pin", fn)
}

// SnapPosition is a generated enum type.
type SnapPosition string

const (
	SnapPositionLeft           SnapPosition = "left"
	SnapPositionRight          SnapPosition = "right"
	SnapPositionTop            SnapPosition = "top"
	SnapPositionBottom         SnapPosition = "bottom"
	SnapPositionMaximize       SnapPosition = "maximize"
	SnapPositionAlmostMaximize SnapPosition = "almost_maximize"
	SnapPositionCenter         SnapPosition = "center"
	SnapPositionLeftThird      SnapPosition = "left_third"
	SnapPositionCenterThird    SnapPosition = "center_third"
	SnapPositionRightThird     SnapPosition = "right_third"
	SnapPositionLeftTwoThirds  SnapPosition = "left_two_thirds"
	SnapPositionRightTwoThirds SnapPosition = "right_two_thirds"
	SnapPositionTopLeft        SnapPosition = "top_left"
	SnapPositionTopRight       SnapPosition = "top_right"
	SnapPositionBottomLeft     SnapPosition = "bottom_left"
	SnapPositionBottomRight    SnapPosition = "bottom_right"
	SnapPositionNext           SnapPosition = "next"
	SnapPositionPrev           SnapPosition = "prev"
)

// SnapParams is the params shape for action "placement.snap (Snap Window)".
type SnapParams struct {
	Position *SnapPosition `json:"position,omitempty"`
	App      *string       `json:"app,omitempty"`
}

// HandleSnap registers a typed handler for action "placement.snap (Snap Window)".
func HandleSnap(p *branchkit.Plugin, fn func(SnapParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "placement.snap", fn)
}

// ToScreenParams is the params shape for action "placement.to_screen (Move Window to Screen)".
type ToScreenParams struct {
	Screen string  `json:"screen"`
	App    *string `json:"app,omitempty"`
}

// HandleToScreen registers a typed handler for action "placement.to_screen (Move Window to Screen)".
func HandleToScreen(p *branchkit.Plugin, fn func(ToScreenParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "placement.to_screen", fn)
}

// UndoParams is the params shape for action "placement.undo (Put Window Back)".
type UndoParams struct {
}

// HandleUndo registers a typed handler for action "placement.undo (Put Window Back)".
func HandleUndo(p *branchkit.Plugin, fn branchkit.ActionHandlerFunc) {
	p.HandleAction("placement.undo", fn)
}
